In [1]:
#importando biblioteca de manipulação de dados: Pandas
import pandas as pd

In [2]:
# Lendo e trazendo para o notebook o conjunto de dados
df = pd.read_csv('certificados_produtos.csv', encoding = 'utf-16', sep = ';', on_bad_lines='skip')
df.head(10)

,NUM_CERTIFICADO,CERTIFICADOR_SIGLA,CERTIFICADOR_RAZAO_SOCIAL,CERTIFICADOR_CNPJ,DATA_EMISSAO,DATA_VALIDADE,CLASSE_PRODUTO,STATUS,EMPRESA_CNPJ,EMPRESA_RAZAO_SOCIAL,EMPRESA_PAPEL,EMPRESA_NOME_FANTASIA,EMPRESA_ENDERECO,EMPRESA_BAIRRO,EMPRESA_CIDADE,EMPRESA_UF,EMPRESA_TELEFONE,EMPRESA_EMAIL,PRODUTO_IMPORTADO,NOME_PAIS
0,0018.24-AE-16,NAVE,NAVÊ CERTIFICADORA DE PRODUTO EIRELI EP. pro...,2.778452e+13,19/04/2024,19/04/2027,Artigos Escolares - PT Inmetro nº 481/2010 / P...,CANCELADO,15631531000150,"KAZAN - COMERCIO, IMPORTACAO E EXPORTACAO LTDA",Solicitante,NaN,RUA TIERS 550,CANINDE,SAO PAULO,SP,NaN,NaN,S,China
1,0018/24-AE-31,NAVE,NAVÊ CERTIFICADORA DE PRODUTO EIRELI EP. pro...,2.778452e+13,20/07/2024,20/07/2027,Artigos Escolares - PT Inmetro nº 481/2010 / P...,CANCELADO,15631531000150,"KAZAN - COMERCIO, IMPORTACAO E EXPORTACAO LTDA",Solicitante,NaN,RUA TIERS 550,CANINDE,SAO PAULO,SP,NaN,NaN,S,China
2,0018/24-AE-37,NAVE,NAVÊ CERTIFICADORA DE PRODUTO EIRELI EP. pro...,2.778452e+13,29/08/2024,29/08/2027,Artigos Escolares - PT Inmetro nº 481/2010 / P...,CANCELADO,15631531000150,"KAZAN - COMERCIO, IMPORTACAO E EXPORTACAO LTDA",Solicitante,NaN,RUA TIERS 550,CANINDE,SAO PAULO,SP,NaN,NaN,S,China
3,00463/2020-BRINQ-1,SARON,Saron Certificações Ltda - ME qualidade1@saron...,2.200360e+13,08/04/2020,08/04/2050,Brinquedos - PT Inmetro nº 321/2009,ATIVO,68168368000105,UNI-ART Import Ltda.,Solicitante,UNI-ART,Av Das Industrias 755 D Ind.,Benedito Storani,Vinhedo,SP,NaN,NaN,S,China
4,0052/2019 R01,BBVQ,BBV Qualidade Ltda. - ME moacir@bbiengenharia...,2.512946e+13,27/11/2023,01/12/2027,Tanques de Carga Rodoviários Destinados ao Tra...,ATIVO,33711712000178,ITS FABRICAÇÃO DE TANQUES S.A,Solicitante/Fabricante,NaN,"Rua Emir Macedo Nogueira , , Cep: 09 nº 282",Jd Ruyce,Diadema,SP,NaN,NaN,N,NaN
5,0076/2020 R01,BBVQ,BBV Qualidade Ltda. - ME moacir@bbiengenharia...,2.512946e+13,28/06/2023,01/07/2027,Veículos Porta-Contêiner e Dispositivos de Fix...,ATIVO,79131918000120,Noma do Brasil Sociedade Anonima,Solicitante/Fabricante,NaN,Rod. BR 376 336 KM 415,Jd Perimetral,Sarandi,PR,NaN,NaN,N,NaN
6,0169/2023,BBVQ,BBV Qualidade Ltda. - ME moacir@bbiengenharia...,2.512946e+13,19/06/2023,19/06/2027,Tanques de Carga Rodoviários Destinados ao Tra...,ATIVO,33711712000178,ITS FABRICAÇÃO DE TANQUES S.A,Solicitante/Fabricante,NaN,"Rua Emir Macedo Nogueira , , Cep: 09 nº 282",Jd Ruyce,Diadema,SP,NaN,NaN,N,NaN
7,0172/2023,BBVQ,BBV Qualidade Ltda. - ME moacir@bbiengenharia...,2.512946e+13,14/07/2023,14/07/2027,Veículos Porta-Contêiner e Dispositivos de Fix...,ATIVO,30481254000130,OLIVO S/A Indústria e Comércio de Implementos ...,Solicitante/Fabricante,OLIVO Implementos,Rua Marta Rossa Savaris 281,Centro,Siderópolis,SC,NaN,NaN,N,NaN
8,0176/25-BQ-05,NAVE,NAVÊ CERTIFICADORA DE PRODUTO EIRELI EP. pro...,2.778452e+13,27/11/2025,27/11/2030,Brinquedos - PT Inmetro nº 563/2016 / PT Inmet...,ATIVO,36999729000160,YA PLAST MANUFATURA E COMERCIO DE PLASTICOS LTDA,Solicitante/Fabricante,NaN,"R VISCONDE DE PARNAIBA, 2913, BRAS, SÃO PAULO ...",NaN,NaN,,NaN,NaN,N,NaN
9,0176/25-BQ-08,NAVE,NAVÊ CERTIFICADORA DE PRODUTO EIRELI EP. pro...,2.778452e+13,27/11/2025,27/11/2030,Brinquedos - PT Inmetro nº 563/2016 / PT Inmet...,ATIVO,36999729000160,YA PLAST MANUFATURA E COMERCIO DE PLASTICOS LTDA,Solicitante/Fabricante,NaN,"R VISCONDE DE PARNAIBA, 2913, BRAS, SÃO PAULO ...",NaN,NaN,,NaN,NaN,N,NaN

In [3]:
# Verificando tamanho da tabela
df.shape

(162048, 20)

In [4]:
# Verificando valores ausentes
df.isna().sum()

NUM_CERTIFICADO                   4
CERTIFICADOR_SIGLA                4
CERTIFICADOR_RAZAO_SOCIAL         4
CERTIFICADOR_CNPJ                 4
DATA_EMISSAO                      4
DATA_VALIDADE                     4
CLASSE_PRODUTO                    4
STATUS                            4
EMPRESA_CNPJ                      4
EMPRESA_RAZAO_SOCIAL             13
EMPRESA_PAPEL                     4
EMPRESA_NOME_FANTASIA         56663
EMPRESA_ENDERECO                  4
EMPRESA_BAIRRO                46027
EMPRESA_CIDADE                16501
EMPRESA_UF                        4
EMPRESA_TELEFONE             147061
EMPRESA_EMAIL                147080
PRODUTO_IMPORTADO                 4
NOME_PAIS                     38058
dtype: int64

In [5]:
# Verificando valores ausents na coluna número do certificado
df[df['NUM_CERTIFICADO'].isna()]

,NUM_CERTIFICADO,CERTIFICADOR_SIGLA,CERTIFICADOR_RAZAO_SOCIAL,CERTIFICADOR_CNPJ,DATA_EMISSAO,DATA_VALIDADE,CLASSE_PRODUTO,STATUS,EMPRESA_CNPJ,EMPRESA_RAZAO_SOCIAL,EMPRESA_PAPEL,EMPRESA_NOME_FANTASIA,EMPRESA_ENDERECO,EMPRESA_BAIRRO,EMPRESA_CIDADE,EMPRESA_UF,EMPRESA_TELEFONE,EMPRESA_EMAIL,PRODUTO_IMPORTADO,NOME_PAIS
101348,NaN,OCAN,Organismo Certificação Acreditação Nacional Lt...,2.206125e+13,19/03/2024,18/03/2029,Brinquedos - PT Inmetro nº 563/2016 / PT Inmet...,ATIVO,13434272000141,PLANETA - IMPORTACAO E DISTRIBUICAO DE BRINQUE...,Solicitante,NaN,AV VASCO MASSAFELI- GALPAO1 RUA A LADO IMPAR A...,JD MARIA TEREZA,COTIA,SP,NaN,NaN,S,China
101350,NaN,OCAN,Organismo Certificação Acreditação Nacional Lt...,2.206125e+13,19/03/2024,18/03/2029,Brinquedos - PT Inmetro nº 563/2016 / PT Inmet...,ATIVO,13434272000141,PLANETA - IMPORTACAO E DISTRIBUICAO DE BRINQUE...,Solicitante,NaN,AV VASCO MASSAFELI- GALPAO1 RUA A LADO IMPAR A...,JD MARIA TEREZA,COTIA,SP,NaN,NaN,S,China
101353,NaN,OCAN,Organismo Certificação Acreditação Nacional Lt...,2.206125e+13,19/03/2024,18/03/2029,Brinquedos - PT Inmetro nº 563/2016 / PT Inmet...,ATIVO,13434272000141,PLANETA - IMPORTACAO E DISTRIBUICAO DE BRINQUE...,Solicitante,NaN,AV VASCO MASSAFELI- GALPAO1 RUA A LADO IMPAR A...,JD MARIA TEREZA,COTIA,SP,NaN,NaN,S,China
101355,NaN,OCAN,Organismo Certificação Acreditação Nacional Lt...,2.206125e+13,19/03/2024,18/03/2029,Brinquedos - PT Inmetro nº 563/2016 / PT Inmet...,ATIVO,13434272000141,PLANETA - IMPORTACAO E DISTRIBUICAO DE BRINQUE...,Solicitante,NaN,AV VASCO MASSAFELI- GALPAO1 RUA A LADO IMPAR A...,JD MARIA TEREZA,COTIA,SP,NaN,NaN,S,China

In [6]:
# Gerando novo dataframe removendo algumas colunas do conjunto inicial (alto número de dados ausentes)
dados = df.drop(columns = ['EMPRESA_NOME_FANTASIA', 'EMPRESA_BAIRRO', 'EMPRESA_TELEFONE', 'EMPRESA_EMAIL'])
dados.head()

,NUM_CERTIFICADO,CERTIFICADOR_SIGLA,CERTIFICADOR_RAZAO_SOCIAL,CERTIFICADOR_CNPJ,DATA_EMISSAO,DATA_VALIDADE,CLASSE_PRODUTO,STATUS,EMPRESA_CNPJ,EMPRESA_RAZAO_SOCIAL,EMPRESA_PAPEL,EMPRESA_ENDERECO,EMPRESA_CIDADE,EMPRESA_UF,PRODUTO_IMPORTADO,NOME_PAIS
0,0018.24-AE-16,NAVE,NAVÊ CERTIFICADORA DE PRODUTO EIRELI EP. pro...,2.778452e+13,19/04/2024,19/04/2027,Artigos Escolares - PT Inmetro nº 481/2010 / P...,CANCELADO,15631531000150,"KAZAN - COMERCIO, IMPORTACAO E EXPORTACAO LTDA",Solicitante,RUA TIERS 550,SAO PAULO,SP,S,China
1,0018/24-AE-31,NAVE,NAVÊ CERTIFICADORA DE PRODUTO EIRELI EP. pro...,2.778452e+13,20/07/2024,20/07/2027,Artigos Escolares - PT Inmetro nº 481/2010 / P...,CANCELADO,15631531000150,"KAZAN - COMERCIO, IMPORTACAO E EXPORTACAO LTDA",Solicitante,RUA TIERS 550,SAO PAULO,SP,S,China
2,0018/24-AE-37,NAVE,NAVÊ CERTIFICADORA DE PRODUTO EIRELI EP. pro...,2.778452e+13,29/08/2024,29/08/2027,Artigos Escolares - PT Inmetro nº 481/2010 / P...,CANCELADO,15631531000150,"KAZAN - COMERCIO, IMPORTACAO E EXPORTACAO LTDA",Solicitante,RUA TIERS 550,SAO PAULO,SP,S,China
3,00463/2020-BRINQ-1,SARON,Saron Certificações Ltda - ME qualidade1@saron...,2.200360e+13,08/04/2020,08/04/2050,Brinquedos - PT Inmetro nº 321/2009,ATIVO,68168368000105,UNI-ART Import Ltda.,Solicitante,Av Das Industrias 755 D Ind.,Vinhedo,SP,S,China
4,0052/2019 R01,BBVQ,BBV Qualidade Ltda. - ME moacir@bbiengenharia...,2.512946e+13,27/11/2023,01/12/2027,Tanques de Carga Rodoviários Destinados ao Tra...,ATIVO,33711712000178,ITS FABRICAÇÃO DE TANQUES S.A,Solicitante/Fabricante,"Rua Emir Macedo Nogueira , , Cep: 09 nº 282",Diadema,SP,N,NaN

In [7]:
dados.isna().sum()

NUM_CERTIFICADO                  4
CERTIFICADOR_SIGLA               4
CERTIFICADOR_RAZAO_SOCIAL        4
CERTIFICADOR_CNPJ                4
DATA_EMISSAO                     4
DATA_VALIDADE                    4
CLASSE_PRODUTO                   4
STATUS                           4
EMPRESA_CNPJ                     4
EMPRESA_RAZAO_SOCIAL            13
EMPRESA_PAPEL                    4
EMPRESA_ENDERECO                 4
EMPRESA_CIDADE               16501
EMPRESA_UF                       4
PRODUTO_IMPORTADO                4
NOME_PAIS                    38058
dtype: int64

In [8]:
dados.shape

(162048, 16)

In [9]:
dados = dados.dropna(subset = ['STATUS', 'NUM_CERTIFICADO', 'CERTIFICADOR_SIGLA'])
dados.isna().sum()

NUM_CERTIFICADO                  0
CERTIFICADOR_SIGLA               0
CERTIFICADOR_RAZAO_SOCIAL        0
CERTIFICADOR_CNPJ                0
DATA_EMISSAO                     0
DATA_VALIDADE                    0
CLASSE_PRODUTO                   0
STATUS                           0
EMPRESA_CNPJ                     0
EMPRESA_RAZAO_SOCIAL             9
EMPRESA_PAPEL                    0
EMPRESA_ENDERECO                 0
EMPRESA_CIDADE               16497
EMPRESA_UF                       0
PRODUTO_IMPORTADO                0
NOME_PAIS                    38054
dtype: int64

In [10]:
dados[dados['EMPRESA_RAZAO_SOCIAL'].isna()]

,NUM_CERTIFICADO,CERTIFICADOR_SIGLA,CERTIFICADOR_RAZAO_SOCIAL,CERTIFICADOR_CNPJ,DATA_EMISSAO,DATA_VALIDADE,CLASSE_PRODUTO,STATUS,EMPRESA_CNPJ,EMPRESA_RAZAO_SOCIAL,EMPRESA_PAPEL,EMPRESA_ENDERECO,EMPRESA_CIDADE,EMPRESA_UF,PRODUTO_IMPORTADO,NOME_PAIS
31518,1305 PIMO,CERTIFIC,INSTITUTO CERTIFICA SOCIEDADE SIMPLES nedela...,3.021829e+13,09/09/2024,08/09/2027,Produção Integrada Agropecuária - PI Brasil - ...,ATIVO,27664490006,NaN,Fabricante,Estr. Municipal Arlindo Ângelo Andreazza s/n,Caxias do Sul,RS,N,NaN
35920,2423 PIUP,CERTIFIC,INSTITUTO CERTIFICA SOCIEDADE SIMPLES nedela...,3.021829e+13,07/02/2025,06/02/2028,Produção Integrada Agropecuária - PI Brasil - ...,ATIVO,36819573049,NaN,Fabricante,Assentamento da Quinta sn,Encruzilhada do Sul,RS,N,NaN
90535,DNV 12SE0107,DNV,DNV GL BUSINESS ASSURANCE AVALIAÇÕES E CERTIFI...,6.035420e+11,10/07/2012,10/07/2042,Equipamentos Elétricos para Atmosferas Explosi...,ATIVO,07053767000128,NaN,Solicitante,,NaN,,S,Estados Unidos
93426,DNV 24.0153,DNV,DNV GL BUSINESS ASSURANCE AVALIAÇÕES E CERTIFI...,6.035420e+11,28/06/2024,28/06/2054,Equipamentos Elétricos para Atmosferas Explosi...,ATIVO,07053767000128,NaN,Solicitante,,NaN,,S,Estados Unidos
127588,LMP 20SE0162,LMP,LMP CERTIFICAÇÕES LTDA CONTATO@LMP...,5.885069e+12,27/07/2020,27/07/2070,Equipamentos Elétricos para Atmosferas Explosi...,ATIVO,05131904811,NaN,Importador,Av. Ibrain Nobre 50,Araraquara,SP,S,Inglaterra
127591,LMP 20SE0163,LMP,LMP CERTIFICAÇÕES LTDA CONTATO@LMP...,5.885069e+12,27/07/2020,27/07/2070,Equipamentos Elétricos para Atmosferas Explosi...,ATIVO,13110587882,NaN,Importador,Av. Professor Vespasiano Veiga 351,Araraquara,SP,S,Inglaterra
127612,LMP 20SE0181,LMP,LMP CERTIFICAÇÕES LTDA CONTATO@LMP...,5.885069e+12,31/07/2020,31/07/2070,Equipamentos Elétricos para Atmosferas Explosi...,ATIVO,13110587882,NaN,Importador,Av. Professor Vespasiano Veiga 351,Araraquara,SP,S,Inglaterra
143664,RBNA 21SE0014X,LMATTOS,Luiz Mattos e Engenheiros Associados Ltda. Ma...,2.801566e+13,02/09/2021,02/09/2070,Equipamentos Elétricos para Atmosferas Explosi...,ATIVO,07053767000128,NaN,Importador,,NaN,,S,NaN
147915,TUV 12SE1432,TUVB,TÜV RHEINLAND DO BRASIL LTDA accredit...,1.950467e+12,23/08/2012,31/12/2079,Equipamentos Elétricos para Atmosferas Explosi...,ATIVO,07599928000183,NaN,Importador,"Rua Alves de Brito, Sl 701",Florianópolis,SC,S,Estados Unidos

In [11]:
# Substituindo os valores ausentes pela frase "Não informado" para as demais colunas que não foram tratadas nos passos anteriores
dados.fillna(value = 'Não Informado', inplace = True)
dados.isna().sum()

NUM_CERTIFICADO              0
CERTIFICADOR_SIGLA           0
CERTIFICADOR_RAZAO_SOCIAL    0
CERTIFICADOR_CNPJ            0
DATA_EMISSAO                 0
DATA_VALIDADE                0
CLASSE_PRODUTO               0
STATUS                       0
EMPRESA_CNPJ                 0
EMPRESA_RAZAO_SOCIAL         0
EMPRESA_PAPEL                0
EMPRESA_ENDERECO             0
EMPRESA_CIDADE               0
EMPRESA_UF                   0
PRODUTO_IMPORTADO            0
NOME_PAIS                    0
dtype: int64

In [12]:
dados.head()

,NUM_CERTIFICADO,CERTIFICADOR_SIGLA,CERTIFICADOR_RAZAO_SOCIAL,CERTIFICADOR_CNPJ,DATA_EMISSAO,DATA_VALIDADE,CLASSE_PRODUTO,STATUS,EMPRESA_CNPJ,EMPRESA_RAZAO_SOCIAL,EMPRESA_PAPEL,EMPRESA_ENDERECO,EMPRESA_CIDADE,EMPRESA_UF,PRODUTO_IMPORTADO,NOME_PAIS
0,0018.24-AE-16,NAVE,NAVÊ CERTIFICADORA DE PRODUTO EIRELI EP. pro...,2.778452e+13,19/04/2024,19/04/2027,Artigos Escolares - PT Inmetro nº 481/2010 / P...,CANCELADO,15631531000150,"KAZAN - COMERCIO, IMPORTACAO E EXPORTACAO LTDA",Solicitante,RUA TIERS 550,SAO PAULO,SP,S,China
1,0018/24-AE-31,NAVE,NAVÊ CERTIFICADORA DE PRODUTO EIRELI EP. pro...,2.778452e+13,20/07/2024,20/07/2027,Artigos Escolares - PT Inmetro nº 481/2010 / P...,CANCELADO,15631531000150,"KAZAN - COMERCIO, IMPORTACAO E EXPORTACAO LTDA",Solicitante,RUA TIERS 550,SAO PAULO,SP,S,China
2,0018/24-AE-37,NAVE,NAVÊ CERTIFICADORA DE PRODUTO EIRELI EP. pro...,2.778452e+13,29/08/2024,29/08/2027,Artigos Escolares - PT Inmetro nº 481/2010 / P...,CANCELADO,15631531000150,"KAZAN - COMERCIO, IMPORTACAO E EXPORTACAO LTDA",Solicitante,RUA TIERS 550,SAO PAULO,SP,S,China
3,00463/2020-BRINQ-1,SARON,Saron Certificações Ltda - ME qualidade1@saron...,2.200360e+13,08/04/2020,08/04/2050,Brinquedos - PT Inmetro nº 321/2009,ATIVO,68168368000105,UNI-ART Import Ltda.,Solicitante,Av Das Industrias 755 D Ind.,Vinhedo,SP,S,China
4,0052/2019 R01,BBVQ,BBV Qualidade Ltda. - ME moacir@bbiengenharia...,2.512946e+13,27/11/2023,01/12/2027,Tanques de Carga Rodoviários Destinados ao Tra...,ATIVO,33711712000178,ITS FABRICAÇÃO DE TANQUES S.A,Solicitante/Fabricante,"Rua Emir Macedo Nogueira , , Cep: 09 nº 282",Diadema,SP,N,Não Informado

In [13]:
# Remoção de linhas duplicadas (certificados duplicados)
dados = dados.drop_duplicates(subset = 'NUM_CERTIFICADO')
dados.shape

(143055, 16)

In [14]:
dados.dtypes

NUM_CERTIFICADO               object
CERTIFICADOR_SIGLA            object
CERTIFICADOR_RAZAO_SOCIAL     object
CERTIFICADOR_CNPJ            float64
DATA_EMISSAO                  object
DATA_VALIDADE                 object
CLASSE_PRODUTO                object
STATUS                        object
EMPRESA_CNPJ                  object
EMPRESA_RAZAO_SOCIAL          object
EMPRESA_PAPEL                 object
EMPRESA_ENDERECO              object
EMPRESA_CIDADE                object
EMPRESA_UF                    object
PRODUTO_IMPORTADO             object
NOME_PAIS                     object
dtype: object

In [15]:
# Transformando datas com vencimento acima do aceitável pelo datetime
date_out = dados['DATA_VALIDADE'].str[6:10].astype(int) >= 2262
dados.loc[date_out, 'DATA_VALIDADE'] = '30/12/2199'

In [16]:
dados[dados['DATA_VALIDADE'] == '12/03/3019']

Empty DataFrame
Columns: [NUM_CERTIFICADO, CERTIFICADOR_SIGLA, CERTIFICADOR_RAZAO_SOCIAL, CERTIFICADOR_CNPJ, DATA_EMISSAO, DATA_VALIDADE, CLASSE_PRODUTO, STATUS, EMPRESA_CNPJ, EMPRESA_RAZAO_SOCIAL, EMPRESA_PAPEL, EMPRESA_ENDERECO, EMPRESA_CIDADE, EMPRESA_UF, PRODUTO_IMPORTADO, NOME_PAIS]
Index: []

In [17]:
# Transformação de colunas de tipo objeto para tipo data 
dados['DATA_EMISSAO'] = pd.to_datetime(dados['DATA_EMISSAO'], format='%d/%m/%Y')
dados['DATA_VALIDADE'] = pd.to_datetime(dados['DATA_VALIDADE'], format='%d/%m/%Y')

In [18]:
df.dtypes

NUM_CERTIFICADO               object
CERTIFICADOR_SIGLA            object
CERTIFICADOR_RAZAO_SOCIAL     object
CERTIFICADOR_CNPJ            float64
DATA_EMISSAO                  object
DATA_VALIDADE                 object
CLASSE_PRODUTO                object
STATUS                        object
EMPRESA_CNPJ                  object
EMPRESA_RAZAO_SOCIAL          object
EMPRESA_PAPEL                 object
EMPRESA_NOME_FANTASIA         object
EMPRESA_ENDERECO              object
EMPRESA_BAIRRO                object
EMPRESA_CIDADE                object
EMPRESA_UF                    object
EMPRESA_TELEFONE              object
EMPRESA_EMAIL                 object
PRODUTO_IMPORTADO             object
NOME_PAIS                     object
dtype: object

In [19]:
dados.head()

,NUM_CERTIFICADO,CERTIFICADOR_SIGLA,CERTIFICADOR_RAZAO_SOCIAL,CERTIFICADOR_CNPJ,DATA_EMISSAO,DATA_VALIDADE,CLASSE_PRODUTO,STATUS,EMPRESA_CNPJ,EMPRESA_RAZAO_SOCIAL,EMPRESA_PAPEL,EMPRESA_ENDERECO,EMPRESA_CIDADE,EMPRESA_UF,PRODUTO_IMPORTADO,NOME_PAIS
0,0018.24-AE-16,NAVE,NAVÊ CERTIFICADORA DE PRODUTO EIRELI EP. pro...,2.778452e+13,2024-04-19,2027-04-19,Artigos Escolares - PT Inmetro nº 481/2010 / P...,CANCELADO,15631531000150,"KAZAN - COMERCIO, IMPORTACAO E EXPORTACAO LTDA",Solicitante,RUA TIERS 550,SAO PAULO,SP,S,China
1,0018/24-AE-31,NAVE,NAVÊ CERTIFICADORA DE PRODUTO EIRELI EP. pro...,2.778452e+13,2024-07-20,2027-07-20,Artigos Escolares - PT Inmetro nº 481/2010 / P...,CANCELADO,15631531000150,"KAZAN - COMERCIO, IMPORTACAO E EXPORTACAO LTDA",Solicitante,RUA TIERS 550,SAO PAULO,SP,S,China
2,0018/24-AE-37,NAVE,NAVÊ CERTIFICADORA DE PRODUTO EIRELI EP. pro...,2.778452e+13,2024-08-29,2027-08-29,Artigos Escolares - PT Inmetro nº 481/2010 / P...,CANCELADO,15631531000150,"KAZAN - COMERCIO, IMPORTACAO E EXPORTACAO LTDA",Solicitante,RUA TIERS 550,SAO PAULO,SP,S,China
3,00463/2020-BRINQ-1,SARON,Saron Certificações Ltda - ME qualidade1@saron...,2.200360e+13,2020-04-08,2050-04-08,Brinquedos - PT Inmetro nº 321/2009,ATIVO,68168368000105,UNI-ART Import Ltda.,Solicitante,Av Das Industrias 755 D Ind.,Vinhedo,SP,S,China
4,0052/2019 R01,BBVQ,BBV Qualidade Ltda. - ME moacir@bbiengenharia...,2.512946e+13,2023-11-27,2027-12-01,Tanques de Carga Rodoviários Destinados ao Tra...,ATIVO,33711712000178,ITS FABRICAÇÃO DE TANQUES S.A,Solicitante/Fabricante,"Rua Emir Macedo Nogueira , , Cep: 09 nº 282",Diadema,SP,N,Não Informado

In [20]:
# Salvando dados limpos em arquivo excel
dados.to_excel('certificados_final4.xlsx', index = False)